In [69]:
'''This is the comment'''

'This is the comment'

In [70]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
result = [sum(x) for x in zip(a,b)]

In [71]:
result

[7, 9, 11, 13, 15]

In [72]:
import numpy as np 
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a+b


array([ 7,  9, 11, 13, 15])

In [73]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.add(a,b)
c

array([ 7,  9, 11, 13, 15])

In [74]:
a = np.array([1,2,3,4,5])
type(a)


numpy.ndarray

In [75]:
a.dtype

dtype('int64')

In [76]:
a = np.array([1,2,3,4,5])

In [77]:
a[1] = 90
a

array([ 1, 90,  3,  4,  5])

In [78]:
a

array([ 1, 90,  3,  4,  5])

In [79]:
a[1] = 33.5 ## numnpy is very strict in datatype 
a

array([ 1, 33,  3,  4,  5])

In [80]:
a.ndim

1

In [81]:
a.shape

(5,)

In [82]:
a.size

5

np.ones()
np.zeros()
np.empty()
np.arrange()

np.ones(shape,dtype=none, order='C')

In [83]:
arr = np.ones(3, dtype=np.int64)

In [84]:
arr

array([1, 1, 1])

In [85]:
arr.shape

(3,)

In [86]:
arr1 = np.ones((3,4), dtype=np.int64)
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [87]:
arr = np.ones(3)

In [88]:
arr

array([1., 1., 1.])

In [89]:
arr = np.zeros((3, 4),dtype=np.int64)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [90]:
np.ones((3,4,3),dtype=np.int64)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

## Creating an array with range of elements
numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

In [91]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [92]:
a = np.arange(1,10,2,dtype=float)
a

array([1., 3., 5., 7., 9.])

add = a+b
sub = a-b
mul = a*b
div = a/b
power = a**b

In [93]:
a = np.array([33,2,3,4])
b = np.array([5,6,72,56])
add = np.add(a,b)
sub = np.subtract(a,b)
mul = np.multiply(a,b)
div = np.divide(a,b)
power = np.pow(a,b)
print('add:',add,'sub:',sub,"mul:",mul,"div:",div,'power:',power)


add: [38  8 75 60] sub: [ 28  -4 -69 -52] mul: [165  12 216 224] div: [6.6        0.33333333 0.04166667 0.07142857] power: [           39135393                  64 2190886001003067041
                   0]


In [94]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
a[0,1]

np.int64(2)

In [96]:
a[1,1]

np.int64(5)

In [97]:
a[1,1] = 10
a

array([[ 1,  2,  3],
       [ 4, 10,  6]])

## slicing 

In [98]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [99]:
arr[1:]

array([2, 3, 4, 5, 6, 7])

In [100]:
arr[:3]

array([1, 2, 3])

In [101]:
arr[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [102]:
arr[0::2]

array([1, 3, 5, 7])

In [103]:
a = np.array([[2,8,4],[1,2,5],[0,4,3]])
a[1,2]

np.int64(5)

In [104]:
arr = np.array([1,2,3,4,5,6,7])
arr[:2:-1]

array([7, 6, 5, 4])

In [105]:
a = np.array([10,11,12,13,14,15])


## Qn 1. Create a 1D array of numbers from 0 to 11
Desired output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Qn 1.2 Print the data type of the array

In [107]:
type(a)

numpy.ndarray

## Qn1.3 Change the dtype to float64

In [108]:
a = a.astype('float64')
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Qn 2. Extract all odd numbers from arr

Input: arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Desired output: array([1, 3, 5, 7, 9])

In [109]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
odd = [x for x in arr if x%2 != 0]
odd

[1, 3, 5, 7, 9]

## Q3. Convert a 1D array to a 2D array with 2 rows
Input: np.arange(10)
Desired Output:array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

In [110]:
arr = np.arange(10)
arr_2d = arr.reshape(2, 5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Q4. Stack arrays a and b vertically
Input a = np.arange(10).reshape(2,-1)b = np.repeat(1, 10).reshape(2,-1) 
Desired Output:> array([[0, 1, 2, 3, 4],> [5, 6, 7, 8, 9],> [1, 1, 1, 1, 1],

In [111]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.vstack((a,b))
d = np.hstack((a,b))
c,d

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]))

## Q5. Get the positions where elements of a and b match

Input:a = [1,2,3,2,3,4,3,4,5,6]b = [7,2,10,2,7,4,9,4,9,8]

Desired Output:> (array([1, 3, 5, 7]),)

In [112]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
matching_index = np.where(a == b)
print(matching_index)


(array([1, 3, 5, 7]),)


## Q6: Swap columns 1 and 2 in the array arr.
Input: arr = np.arange(9).reshape(3,3)

In [113]:
arr = np.arange(9).reshape(3,3)
print(f'before swaping:,{arr}')
arr[:, [0, 1]] = arr[:, [1, 0]]
print(f'after swaping:,{arr}')

before swaping:,[[0 1 2]
 [3 4 5]
 [6 7 8]]
after swaping:,[[1 0 2]
 [4 3 5]
 [7 6 8]]


## Q7: Swap rows 1 and 2 in the array 
arr:Input:arr = np.arange(9).reshape(3,3)


In [114]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
arr[[0, 1], :] = arr[[1, 0], :]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## Q8. Reverse the rows of a 2D array arr.
Input:
arr = np.arange(9).reshape(3,3)

In [116]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
reversed_arr = arr[::-1]
print(reversed_arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## Q9. Create a 2D array of shape 5x3 to contain random decimalnumbers between 5 and 10.

In [118]:
arr = np.random.uniform(5, 10, size=(5, 3))
print(arr)

[[6.95735292 6.40056465 7.31325245]
 [8.2267903  6.8313629  5.67098181]
 [8.41206747 8.69796816 9.62685207]
 [5.59788707 8.79208095 5.56078825]
 [5.00672567 9.73117564 7.49024254]]


## Q10: Consider the below arrayarray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
## Q10.1 Create a slice of the array containing the following values: array([5, 6,7])

In [119]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
sliced_arr = arr[5:8]
print(sliced_arr)

[5 6 7]


## Q10.2 Modify the given array to the below format array([ 0, 1, 2, 3, 4, 12, 12, 12, 8, 9])

In [121]:
arr[5:8] = 12
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## Q11: Drop all nan values from a 1D numpy array

Input:a = [1,2,3,np.nan,5,6,7,np.nan]

Desired Output:array([ 1., 2., 3., 5., 6., 7.])

In [130]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [135]:
b = a[~np.isnan(a)]
b

array([1., 2., 3., 5., 6., 7.])

## Q12: Create an empty, ones and zero array with 6, 3, and 4elements respectively

In [124]:
# Empty array with 6 elements
empty_arr = np.empty(6)

# Ones array with 3 elements
ones_arr = np.ones(3)

# Zeros array with 4 elements
zeros_arr = np.zeros(4)

print("Empty array:\n", empty_arr)
print("Ones array:\n", ones_arr)
print("Zeros array:\n", zeros_arr)


Empty array:
 [1. 2. 3. 5. 6. 7.]
Ones array:
 [1. 1. 1.]
Zeros array:
 [0. 0. 0. 0.]


## Q13: Create a 4x4 array with all elements value set to 23.67

In [128]:
arr = np.full((4, 4), 23.67)
arr

array([[23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67]])

## Qn14: Create an array with eight values that are spaced linearly inthe [13, 27] interval

In [129]:
array = np.linspace(13,27, 8)
array

array([13., 15., 17., 19., 21., 23., 25., 27.])